import { Inter } from 'next/font/google';
import './globals.css';
import NextAuth from './providers/NextAuth';
import { UtilsProvider } from '@/app/providers/UtilContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuth>
          <UtilsProvider>
            <div className="w-full flex flex-col items-center justify-start relative">
              {children}
            </div>
          </UtilsProvider>
        </NextAuth>
      </body>
    </html>
  );
}
